#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-actionpack
Version  : 4.2.6
Release  : 10
URL      : https://rubygems.org/downloads/actionpack-4.2.6.gem
Source0  : https://rubygems.org/downloads/actionpack-4.2.6.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-rdoc

%description
= Action Pack -- From request to response
Action Pack is a framework for handling and responding to web requests. It
provides mechanisms for *routing* (mapping request URLs to actions), defining
*controllers* that implement actions, and generating responses by rendering
*views*, which are templates of various formats. In short, Action Pack
provides the view and controller layers in the MVC paradigm.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n actionpack-4.2.6
gem spec %{SOURCE0} -l --ruby > rubygem-actionpack.gemspec

%build
export LANG=C
gem build rubygem-actionpack.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
actionpack-4.2.6.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/actionpack-4.2.6.gem
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/CHANGELOG.md
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/MIT-LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/README.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/abstract_controller.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/abstract_controller/asset_paths.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/abstract_controller/base.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/abstract_controller/callbacks.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/abstract_controller/collector.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/abstract_controller/helpers.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/abstract_controller/logger.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/abstract_controller/railties/routes_helpers.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/abstract_controller/rendering.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/abstract_controller/translation.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/abstract_controller/url_for.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_controller.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_controller/base.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_controller/caching.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_controller/caching/fragments.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_controller/log_subscriber.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/conditional_get.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/cookies.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/data_streaming.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/etag_with_template_digest.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/exceptions.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/flash.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/force_ssl.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/head.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/helpers.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/hide_actions.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/http_authentication.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/implicit_render.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/instrumentation.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/live.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/mime_responds.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/params_wrapper.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/rack_delegation.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/redirecting.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/renderers.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/rendering.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/request_forgery_protection.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/rescue.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/streaming.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/strong_parameters.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/testing.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_controller/metal/url_for.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_controller/middleware.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_controller/model_naming.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_controller/railtie.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_controller/railties/helpers.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_controller/test_case.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/http/cache.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/http/filter_parameters.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/http/filter_redirect.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/http/headers.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/http/mime_negotiation.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/http/mime_type.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/http/mime_types.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/http/parameter_filter.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/http/parameters.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/http/rack_cache.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/http/request.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/http/response.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/http/upload.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/http/url.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/journey.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/journey/backwards.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/journey/formatter.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/journey/gtg/builder.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/journey/gtg/simulator.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/journey/gtg/transition_table.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/journey/nfa/builder.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/journey/nfa/dot.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/journey/nfa/simulator.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/journey/nfa/transition_table.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/journey/nodes/node.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/journey/parser.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/journey/parser.y
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/journey/parser_extras.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/journey/path/pattern.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/journey/route.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/journey/router.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/journey/router/strexp.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/journey/router/utils.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/journey/routes.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/journey/scanner.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/journey/visitors.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/journey/visualizer/fsm.css
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/journey/visualizer/fsm.js
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/journey/visualizer/index.html.erb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/callbacks.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/cookies.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/debug_exceptions.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/exception_wrapper.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/flash.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/params_parser.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/public_exceptions.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/reloader.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/remote_ip.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/request_id.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/session/abstract_store.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/session/cache_store.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/session/cookie_store.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/session/mem_cache_store.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/show_exceptions.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/ssl.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/stack.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/static.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_request_and_response.text.erb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_source.erb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/_trace.text.erb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/diagnostics.text.erb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/layout.erb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/missing_template.html.erb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/missing_template.text.erb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/routing_error.html.erb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/routing_error.text.erb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/template_error.html.erb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/template_error.text.erb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/unknown_action.html.erb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/rescues/unknown_action.text.erb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/routes/_route.html.erb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/middleware/templates/routes/_table.html.erb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/railtie.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/request/session.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/request/utils.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/routing.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/endpoint.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/inspector.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/mapper.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/polymorphic_routes.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/redirection.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/route_set.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/routes_proxy.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/routing/url_for.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/testing/assertions.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/testing/assertions/dom.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/testing/assertions/response.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/testing/assertions/routing.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/testing/assertions/selector.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/testing/assertions/tag.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/testing/integration.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/testing/test_process.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/testing/test_request.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_dispatch/testing/test_response.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_pack.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_pack/gem_version.rb
/usr/lib64/ruby/gems/2.3.0/gems/actionpack-4.2.6/lib/action_pack/version.rb
/usr/lib64/ruby/gems/2.3.0/specifications/actionpack-4.2.6.gemspec
